SimSettings: avoid NPE
Don't assume getPhoneAccount doesn't return null just because you're passing a
non-null argument.

Avoids:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.telecom.PhoneAccount.getLabel()' on a null object reference
       at com.android.settings.sim.SimSettings.updateCallValues(SimSettings.java:299)
       at com.android.settings.sim.SimSettings.updateActivitesCategory(SimSettings.java:237)
       at com.android.settings.sim.SimSettings.updateAllOptions(SimSettings.java:222)
       at com.android.settings.sim.SimSettings.updateSubscriptions(SimSettings.java:217)
       at com.android.settings.sim.SimSettings.-wrap4(SimSettings.java)
       at com.android.settings.sim.SimSettings$1.onSubscriptionsChanged(SimSettings.java:175)
       at android.telephony.SubscriptionManager$OnSubscriptionsChangedListener$1.handleMessage(SubscriptionManager.java:397)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5461)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Change-Id: Ibdb5a978744a8f3e5dd916d08297a07d98aca5be

Conflicts:
	src/com/android/settings/sim/SimSettings.java